### PR TITLE
Update MBL commit #

### PR DESCRIPTION
**Pull request by AntoineGautier**
Related to MBL PR #3540 and #360.
#360 shall remain open: this PR only includes a workaround.

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@AntoineGautier See my comment in issue #360.

**Comment by AntoineGautier** [comment]
@JayHuLBL See the explanation at https://github.com/lbl-srg/ctrl-flow-dev/issues/360#issuecomment-1779228937.

FYI, I updated again MBL commit to the most recent one, as some refactoring of the actuator components used in the templates was recently merged.

**Comment by JayHuLBL** [comment]
@AntoineGautier The changes looks good. Should I merge it?

**Comment by AntoineGautier** [comment]
@JayHuLBL Yes, you can merge to staging.

**Pull request merged**
