### PR TITLE
Updated production site deployment workflow

### LINKED ISSUE #366: Production site deployment failed
The production site deployment failed with the error:
Screenshot 2023-10-19 at 3 34 30 PM

This issue is to correct the production site deployment workflow.

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #366.
### Description
- [x] Updated production site deployment workflow

### CODE REVIEW

**Comment by AntoineGautier** [comment]
@JayHuLBL There is an issue on the current staging branch, see https://github.com/lbl-srg/ctrl-flow-dev/issues/360#issuecomment-1772326895. I am adding the patch on MBL and will update MBL commit hash once this is done.

Also, I noticed that the order of the systems at https://staging.ctrl-flow.lbl.gov/#/systems is not the same as the one I have locally (AHU before zone equipment). Can you look into that?

**Comment by AntoineGautier** [comment]
@JayHuLBL There is still an issue with the current staging branch, which shall not be merged yet. The sections pertaining to relief damper control (w/o fan) are not included in the exported documentation. I will investigate and propose a fix.

**Comment by AntoineGautier** [comment]
@JayHuLBL I checked the documentation export with the following AHU options:

- Separate dampers for ventilation and economizer, with airflow measurement station
- Modulating relief damper without fan

The documents generated by the staging and main versions are identical. 
This is ready to merge on my end.

**Comment by JayHuLBL** [comment]
@AntoineGautier Thanks for the review. I will merge it.

**Pull request merged**
